let money = prompt("сколько у вас с собой есть денег?")
parseFloat (money)
let numApple = prompt("сколько вы купили яблок?")
parseFloat (numApple)
let numBread = prompt("сколько вы купили батонов хлеба?")
parseFloat (numBread)
let priceApple = prompt("сколько стоит одно яблоко?")
parseFloat (priceApple)
let priceBread = prompt("сколько стоит один батон хлеба?")
parseFloat (priceBread)
document.write(money>=(numApple*priceApple + numBread*priceBread));